# Generated by Django 5.1.4 on 2026-07-07 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('awareness', 'Awareness Drive'), ('hackathon', 'Hackathon'), ('cleanliness_drive', 'Cleanliness Drive (Swachh Bharat)'), ('blood_camp', 'Blood Donation Camp'), ('plantation', 'Plantation Drive'), ('relief_collection', 'Relief Collection'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaigns/banners/')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='published', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_organized', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('team_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='registered', max_length=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['category', 'status'], name='campaigns_c_categor_239956_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['city'], name='campaigns_c_city_e20f36_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignregistration',
            index=models.Index(fields=['campaign', 'user'], name='campaigns_c_campaig_436da9_idx'),
        ),
    ]
