# Generated by Django 5.1.4 on 2026-07-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_created_by_notification_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('missing_person_alert', 'Missing Person Alert'), ('sos_alert', 'SOS Alert'), ('disaster_alert', 'Disaster Alert'), ('blood_request', 'Blood Request'), ('volunteer_assignment', 'Volunteer Assignment'), ('campaign_update', 'Campaign Update'), ('community_post', 'Community Post'), ('system', 'System')], max_length=30),
        ),
    ]
