# Generated by Django 5.1.4 on 2026-07-07 13:25

import apps.missing_persons.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPersonReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('public_slug', models.SlugField(default=apps.missing_persons.models._generate_slug, editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('clothing_description', models.TextField(blank=True)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('last_seen_at', models.DateTimeField()),
                ('medical_conditions', models.TextField(blank=True)),
                ('languages_spoken', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('verified', 'Verified'), ('found', 'Found'), ('closed', 'Closed')], default='missing', max_length=10)),
                ('face_embedding', models.JSONField(blank=True, help_text='Reserved for AI face-matching pipeline.', null=True)),
                ('ai_summary', models.TextField(blank=True, help_text='Auto-generated report summary.')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='missing_persons/qr_codes/')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_person_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MissingPersonPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='missing_persons/photos/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='missing_persons.missingpersonreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='missing_persons.missingpersonreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SightingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField()),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('sighted_at', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='missing_persons/sightings/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='missing_persons.missingpersonreport')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sighted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='missingpersonreport',
            index=models.Index(fields=['status'], name='missing_per_status_666eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='missingpersonreport',
            index=models.Index(fields=['public_slug'], name='missing_per_public__ed6e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='missingpersonreport',
            index=models.Index(fields=['name', 'age'], name='missing_per_name_3faaef_idx'),
        ),
    ]
