# Generated by Django 5.1.4 on 2026-07-07 13:25

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('medical', 'Medical'), ('search_rescue', 'Search & Rescue'), ('animal_rescue', 'Animal Rescue'), ('food_distribution', 'Food Distribution'), ('transport', 'Transport')], max_length=30), blank=True, default=list, size=None)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('reputation_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_verified', 'is_available'], name='volunteers__is_veri_88b295_idx')],
            },
        ),
    ]
