# Generated by Django 5.1.4 on 2026-07-07 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('name', models.CharField(max_length=200)),
                ('station_code', models.CharField(max_length=50, unique=True)),
                ('jurisdiction_area', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseForwardRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('missing_person', 'Missing Person'), ('missing_child', 'Missing Child'), ('missing_elderly', 'Missing Elderly'), ('sos', 'SOS')], max_length=20)),
                ('report_id', models.UUIDField(help_text='Primary key of the source report (polymorphic across report types).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('reference_number', models.CharField(blank=True, help_text='Reference issued by the police system.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_cases', to='police.policestation')),
            ],
        ),
        migrations.AddIndex(
            model_name='policestation',
            index=models.Index(fields=['city', 'is_active'], name='police_poli_city_4fab23_idx'),
        ),
        migrations.AddIndex(
            model_name='caseforwardrecord',
            index=models.Index(fields=['report_type', 'report_id'], name='police_case_report__efd2a5_idx'),
        ),
    ]
