# Generated by Django 5.1.4 on 2026-07-07 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingElderlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='missing_elderly/photos/')),
                ('has_dementia', models.BooleanField(default=False)),
                ('has_alzheimers', models.BooleanField(default=False)),
                ('medical_history', models.TextField(blank=True)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('last_seen_at', models.DateTimeField()),
                ('emergency_button_pressed', models.BooleanField(default=False, help_text='Set when the large in-app emergency button is used.')),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('verified', 'Verified'), ('found', 'Found'), ('closed', 'Closed')], default='missing', max_length=10)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_elderly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='missing_eld_status_129412_idx')],
            },
        ),
    ]
